// sentences.js 240923_1813
const sentencesRegistry = {
    "elasticDemand": [
        `The reason why pushing prices into the elastic range of the demand curve ensures higher revenues is tied to how consumers react to price changes ___ In the inelastic range of the demand curve a price increase results in a smaller percentage decrease in quantity demanded ___ This means people will still buy relatively the same amount even if prices go up but the total revenue might not grow significantly and increasing prices too much can eventually lead to losing customers or overpricing the product compared to competitors`,
        `However when you push prices into the elastic range a small price decrease causes a larger percentage increase in the quantity demanded ___ In other words consumers respond more sensitively to price changes ___ Since the increase in quantity demanded is proportionally larger than the decrease in price total revenue increases`,
        `This strategy works because youre pricing at a point where people are more likely to buy more when the price drops leading to higher overall revenue despite lower prices per unit ___ Markup pricing doesnt take this into account which is why relying on it in inelastic demand situations may lead to nonoptimal profits ___ The optimal strategy is to find a price where you maximize total revenue by capitalizing on consumer behavior in the elastic portion of the demand curve`
    ],
    "gameTheoryEssentials": [
        `strategic_uncertainty_ bro_ this is the essence of chess in life_ when youre playing any game_ this is the paranoia level dialed up to eleven_ its not just you guessing rock paper_ scissors_q_M but the entire scope of game theory uncertainty_ think about cold war nuclear strategies_this isnt just your opponent is next move_ but wondering if they even plan to make a move or if they_re bluffing_ in politics_ in markets_ this is where you_re stuck analyzing what they know_ what they think you know_ and what you think they think you know_ infinite recursion_ you trying to solve for every possible outcome while second-guessing every micro-action_ picture game of thrones_s littlefinger_ always plotting_ but never revealing his hand_ yet everyone is trying to figure him out_ wondering where his allegiances lie_ its that dirty mind game chess match where nothing is ever certain_ you ain_t just dealing with randomness_ you_re dealing with informed randomness_ and that_s the key_`,
        `strategic_voting_ if you thought this was just rolling dice on a ballot_ bruh_ youre sorely mistaken_ rollback analysis_ it_s about making decisions today that look good but only because you know they will pay off down the road_ imagine a coalition government_ where small parties align their votes not to win today but to block a bigger threat tomorrow_ youre out here trying to leverage your tiny bit of power by swinging votes in ways that dont benefit you right away but kill off worse outcomes later_ its long-game thinking with minimal moves_ its playing risk and making alliances_ not to win right now_ but to not get wiped out next turn_ youre voting tactically to maintain an equilibrium where your survival is guaranteed_`,
        `strategy_ this aint just picking random moves_ man_ this is the meta-plan_ think sun tzu here_ big brain warfare tactics_ all warfare is based on deception a strategy is where you go full tactician mode_ predicting moves ten turns ahead_ ever wonder why pros in games like starcraft crush newbs so easily_ they have got the entire map memorized_ they have got every potential path to victory mapped out_ and they know your counters before you have even built your base_ in a game_ your strategy is locking in a plan that cannot easily be countered no matter how wild the variables get_ youre not just reacting to your opponent_ youre orchestrating their downfall without them even realizing it_ think magnus carlsen playing ten steps ahead in chess_ you gotta create a strategy so airtight_ no matter what anyone else does_ you have already accounted for it_ checkmate_ losers_`,
        `subgame_ oh_ you thought this was just a side quest_q_M nah_ bro_ subgames are where the real action happens_ imagine youre in a huge-ass rpg like final fantasy or some mmorpg_ the subgames are those mini-conflicts that seem insignificant until you realize that the outcome actually shifts the entire grand scheme of things_ subgames start at any non-initial node_ meaning you have deviated from the core game_ but what happens here_ the consequences ripple out into the main plot_ you might be on a side mission_ but you just recruited the best damn character in the game without realizing it_ or you have tripped into a death spiral that screws you for the rest of the match_ these nodes are pivotal_ mess it up in one_ and the entire game is outcome changes_`,
        `spe_subgame-perfect_equilibrium_ this is real gangster-level game theory_ you dont just play the game_ you play every possible variation of the game_ making zero mistakes at any level_ its like rollback but on every subgame and main game level_ every choice is calculated like a mathematical proof_ imagine solving not just one equation but every sub-equation that makes up the entire solution set_ matrix-level shit_ bro_ no move goes unchecked_ every branch of the game tree is solid_ and there is no room for error_ this is the strategy that prevents your opponent from exploiting any loophole in your plan_ you make sure that even in subgames_ your strategy is bulletproof_ that is pro-gamer mentality_`,
        `successive_elimination_of_dominated_strategies_ this one is literally wiping away the garbage choices until only the good ones remain_ imagine youre playing a game like magic the gathering_ you got all these cards_ but some are trash in the current meta_ successive elimination is basically the process of narrowing down your deck to the absolute fire cards that dominate in the game_ its removing all the clutter_ like cleaning up your room after years of hoarding junk_ by the end of it_ youre left with nothing but game-winning strategies_ its a process of purging your options_one by one_until only the supreme strategies stand_`,
        `ultimatum_game_ this game will show you the cutthroat nature of negotiation_ you say_ take this offer or eat nothing we both walk away empty-handed_ it_s a zero-sum setup where you are essentially forcing someone to either cave in or suffer_ its hardcore bargaining_ the kind you see in high-stakes diplomacy or even corporate mergers_ someone holds all the cards_ and they are basically like_ take this five percent or i will make sure nobody wins_ and what is crazy_ people actually take the lowball offer when they think its their last chance_ it_s the final power move_either accept a raw deal or leave with nada_`,
        `utility_function_ now_ let is dig into some real math-shit here_ utility isnt just how much cash you stack_ its your internal gauge for how much you value different outcomes_ this applies to risk_ losses_ and gains_ its non-linear_ meaning you dont react to a one hundred dollars win the same way you react to a one hundred dollars loss_ this is where risk aversion comes into play_ youre not purely about stacking numbers_ you_re about calculating how much each situation weighs against your internal feelings about risk_ risk-averse people would give up a little gain to avoid a bigger loss_ and the utility function quantifies that in a way that your brain can comprehend mathematically_ it explains why people will insure their one hundred dollars iphone case but won’t save for retirement_q_M they fear certain losses more than long-term unknowns_`
    ],
    "mobKnowledge": [
        `strategic_uncertainty_ bro_ this is the essence of chess in life_ when youre playing any game_ this is the paranoia level dialed up to eleven_ its not just you guessing rock paper_ scissors_q_M but the entire scope of game theory uncertainty_ think about cold war nuclear strategies_this isnt just your opponent is next move_ but wondering if they even plan to make a move or if they_re bluffing_ in politics_ in markets_ this is where you_re stuck analyzing what they know_ what they think you know_ and what you think they think you know_ infinite recursion_ you trying to solve for every possible outcome while second-guessing every micro-action_ picture game of thrones’ littlefinger_ always plotting_ but never revealing his hand_ yet everyone is trying to figure him out_ wondering where his allegiances lie_ its that dirty mind game chess match where nothing is ever certain_ you ain_t just dealing with randomness_ you_re dealing with informed randomness_ and that_s the key_`,
        `strategic_voting_ if you thought this was just rolling dice on a ballot_ bruh_ youre sorely mistaken_ rollback analysis_ it_s about making decisions today that look good but only because you know they will pay off down the road_ imagine a coalition government_ where small parties align their votes not to win today but to block a bigger threat tomorrow_ youre out here trying to leverage your tiny bit of power by swinging votes in ways that dont benefit you right away but kill off worse outcomes later_ its long-game thinking with minimal moves_ its playing risk and making alliances_ not to win right now_ but to not get wiped out next turn_ youre voting tactically to maintain an equilibrium where your survival is guaranteed_`,
        `strategy_ this aint just picking random moves_ man_ this is the meta-plan_ think sun tzu here_ big brain warfare tactics_ all warfare is based on deception a strategy is where you go full tactician mode_ predicting moves ten turns ahead_ ever wonder why pros in games like starcraft crush newbs so easily_ they have got the entire map memorized_ they have got every potential path to victory mapped out_ and they know your counters before you have even built your base_ in a game_ your strategy is locking in a plan that cannot easily be countered no matter how wild the variables get_ youre not just reacting to your opponent_ youre orchestrating their downfall without them even realizing it_ think magnus carlsen playing ten steps ahead in chess_ you gotta create a strategy so airtight_ no matter what anyone else does_ you have already accounted for it_ checkmate_ losers_`,
        `subgame_ oh_ you thought this was just a side quest_q_M nah_ bro_ subgames are where the real action happens_ imagine youre in a huge-ass rpg like final fantasy or some mmorpg_ the subgames are those mini-conflicts that seem insignificant until you realize that the outcome actually shifts the entire grand scheme of things_ subgames start at any non-initial node_ meaning you have deviated from the core game_ but what happens here_ the consequences ripple out into the main plot_ you might be on a side mission_ but you just recruited the best damn character in the game without realizing it_ or you have tripped into a death spiral that screws you for the rest of the match_ these nodes are pivotal_ mess it up in one_ and the entire game is outcome changes_`,
        `spe_subgame-perfect_equilibrium_ this is real gangster-level game theory_ you dont just play the game_ you play every possible variation of the game_ making zero mistakes at any level_ its like rollback but on every subgame and main game level_ every choice is calculated like a mathematical proof_ imagine solving not just one equation but every sub-equation that makes up the entire solution set_ matrix-level shit_ bro_ no move goes unchecked_ every branch of the game tree is solid_ and there is no room for error_ this is the strategy that prevents your opponent from exploiting any loophole in your plan_ you make sure that even in subgames_ your strategy is bulletproof_ that is pro-gamer mentality_`,
        `successive_elimination_of_dominated_strategies_ this one is literally wiping away the garbage choices until only the good ones remain_ imagine youre playing a game like magic the gathering_ you got all these cards_ but some are trash in the current meta_ successive elimination is basically the process of narrowing down your deck to the absolute fire cards that dominate in the game_ its removing all the clutter_ like cleaning up your room after years of hoarding junk_ by the end of it_ youre left with nothing but game-winning strategies_ its a process of purging your options_one by one_until only the supreme strategies stand_`,
        `ultimatum_game_ this game will show you the cutthroat nature of negotiation_ you say_ take this offer or eat nothing we both walk away empty-handed_ it_s a zero-sum setup where you are essentially forcing someone to either cave in or suffer_ its hardcore bargaining_ the kind you see in high-stakes diplomacy or even corporate mergers_ someone holds all the cards_ and they are basically like_ take this five percent or i will make sure nobody wins_ and what is crazy_ people actually take the lowball offer when they think its their last chance_ it_s the final power move_either accept a raw deal or leave with nada_`,
        `utility_function_ now_ let is dig into some real math-shit here_ utility isnt just how much cash you stack_ its your internal gauge for how much you value different outcomes_ this applies to risk_ losses_ and gains_ its non-linear_ meaning you dont react to a one hundred dollars win the same way you react to a one hundred dollars loss_ this is where risk aversion comes into play_ youre not purely about stacking numbers_ you_re about calculating how much each situation weighs against your internal feelings about risk_ risk-averse people would give up a little gain to avoid a bigger loss_ and the utility function quantifies that in a way that your brain can comprehend mathematically_ it explains why people will insure their one hundred dollars iphone case but won’t save for retirement_q_M they fear certain losses more than long-term unknowns_`
    ],
    "fundamentalismVsConsequentialism": [
        `The key difference between a fundamentalist and a consequentialist lies in how they judge the morality or rightness of an action_`,
        `Fundamentalist_ A fundamentalist typically adheres to absolute principles or rules often derived from religious or ideological texts that are seen as unchanging and universal_ For them an action is right or wrong based on whether it aligns with these core principles regardless of the outcome_ Their focus is on moral absolutes certain things are always right or wrong no matter what happens as a result_ The ends do not justify the means_ For instance lying would always be wrong no matter if it could save someones life because the principle like a commandment or religious rule says lying is immoral_`,
        `Example_ A religious fundamentalist may believe that stealing is wrong under any circumstance because their scripture or doctrine says so_ Even if stealing food would save a starving child the act of stealing is seen as inherently wrong and unacceptable_`,
        `Consequentialist_ A consequentialist on the other hand judges actions by their outcomes or consequences_ For them what makes an action right or wrong is the result it produces_ If an action leads to a good outcome or maximizes positive consequences like happiness wellbeing or the greater good it is considered morally right even if the action itself might break some traditional rule_ The ends do justify the means in this view depending on the result_`,
        `Example_ A consequentialist might argue that stealing food to feed a starving child is morally right because the consequence saving a life outweighs the wrongness of stealing_ The morality of the action is determined by the benefit or harm it causes_`,
        `Summary_ Fundamentalist_ Morality is based on adherence to fixed principles regardless of consequences_`,
        `Consequentialist_ Morality is based on the outcome or consequences of actions where good results can justify actions that might otherwise be seen as wrong_`
    ],
    "alwaysSayLess": [
        `ALWAYS SAY LESS THAN NECESSARY JUDGMENT_ When you are trying to impress people with words the more you say the more common you appear and the less in control_ Even if you are saying something banal it will seem original if you make it vague openended and sphinxlike_ Powerful people impress and intimidate by saying less_ The more you say the more likely you are to say something foolish_`
    ],
    "talebOnPractice": [
        `Taleb walks in immediately starts shitting on your whole mindset`,
        `You think youll perform under pressure without practice What are you an intellectual yet idiot`,
        `Taleb would body you in two sentences flat_ This guys whole Incerto series is basically a massive roast of people who overestimate their abilities while underestimating risk_ Hes got a hardon for skin in the game and you out here thinking you can just skip putting in the reps when the stakes are low_`,
        `Talebs point_ Youre fragile as hell and life will expose that fragility the minute something unexpected hits_ You dont prep for the big game during the big game moron_ You prep for it when nobodys watching and when theres no risk of getting your head blown off_ Hes got an entire section in Antifragile about how systems and people only become stronger when they take regular small hits_`,
        `skips small hits gets decapitated when life hits hard`,
        `But I was supposed to succeed`,
        `Bro youre living in some Platonic ideal world where you think youll suddenly be better when the stakes are high but Talebs gonna roll up laugh in your face and say The only way youll survive high stakes is if youve been forging yourself in lowstakes practice_ Thats how you get antifragile you get better through mistakes and exposure to risk but only if the stakes arent so high that you get fucking wrecked_`,
        `I dont need to practice Ill just be better when it matters`,
        `Taleb slams you with The Black Swan You dumb fuck rare events will wreck your unprepared ass`,
        `Lets talk Black Swan for a second_ Talebs whole deal is that highstakes situations are inherently unpredictable and chaotic_ If youre not hardened by grinding in lowstakes situations youre like that intellectual idiot who thinks they can predict everything only to get bodied by some random chaos that you didnt see coming_`,
        `No practice Big moment arrives Total annihilation`,
        `Taleb hates people who act like theory alone will get them through the tough moments_ Hes all about realworld exposure tinkering and getting your hands dirty_ No room for safespace philosophers or armchair quarterbacks_ Hed probably say something like Youre fragile and only a fool would think they can bypass the pain of practice and still perform when it counts_`,
        `Tries to skip practice Taleb hands you Fooled by Randomness Bro your whole life is a coin flip without preparation`,
        `Practice is how you simulate the hits youre gonna take later when the cost of failure isnt just your pride but your livelihood or worse_ Taleb would say stop being fragile or youre gonna get eaten alive when life throws that highstakes curveball at you_ Youll be another name in his chapter about idiots who didnt prepare for rare events_`,
        `No skin in the game No practice Life suckerpunches you into oblivion`,
        `Talebs perspective Put the reps in now or enjoy becoming a statistic later`
    ],
};
